### ISSUE TITLE
Create high-level design doc/diagram for ssh_scan as a service

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#228]
Had a discussion with @pwnbus and @gdestuynder today about how we would like to architect ssh_scan as a service.

Basic component level would require the following:
- Web UI (web head)
- API + DB + Scheduler/Queue (Engine)
- Scanner (Worker)

I have a todo to work this up into a draft diagram of sorts and socialize it among EIS mentors, ssh_scan contributors/users, MWoS team, and really anyone who cares for feedback.

**Comment by claudijd** [comment]
<img width="1373" alt="screen shot 2016-09-27 at 7 58 26 pm" src="https://cloud.githubusercontent.com/assets/794283/18896086/d0df1996-84ec-11e6-9518-5786d2cedd3d.png">

**Comment by claudijd** [comment]
<img width="1318" alt="screen shot 2016-09-27 at 8 00 53 pm" src="https://cloud.githubusercontent.com/assets/794283/18896127/224a6c86-84ed-11e6-90c9-a8fb00ab5875.png">

**Comment by claudijd** [comment]
Assumptions/thoughts:
- All HTTPS endpoints would subscribe to our TLS (Modern) and Web Security Guidelines (A+)
  - https://wiki.mozilla.org/Security/Server_Side_TLS
  - https://wiki.mozilla.org/Security/Guidelines/Web_Security
- API/Scheduler/Queue/DB might live on the same system in phase 1, but could be separated
- Workers would follow publisher/subscriber model
- Postgres would be used for datastore because of easy JSON handling/querying

**Comment by claudijd** [comment]
Once we get sufficient feedback from stakeholders, the next steps here would be to break down the components and produce design documents for each.  We are leaning toward using the Observatory web front end for the web component, so we'll direct all of our effort to backend components with the exception of the API.

**Comment by agaurav77** [comment]
@claudijd Great idea!

A major portion in this idea would still depend on #61 (worker pool, scheduler etc).

**Comment by claudijd** [comment]
@agaurav77 yeah, this is more or less just providing high-level view so all the individual components will mate up in the end.

**Comment by jvehent** [comment]
A few thoughts:

The TLS Observatory actually started with a design very similar to this, and we eventually tuned it down to something easier to manage. MIG still has that design, and if [I could redo it all over](https://github.com/mozilla/mig/issues/238), I'd remove a bunch of extra complexity.

The problem of the api/queue/worker model is code complexity in the synchronization of jobs: since everything is asynchronous, you need to keep track of pending tasks in a database anyway, otherwise you don't know what to tell the user that's waiting behind the API. It also puts a lot of pressure on infrastructure management. You do gain scalability, but do you really need to create 20 extra workers a day during pick time? probably not...

If you can put everything into one process, it will make your life a lot easier: have the API spin up a job, monitor it, and grab the results directly from stdout. It's a bit ugly, but it works and is simpler to manage.

If you must separate the scanner out of the API, and you only need to pass messages around to trigger scanning jobs, you can use postgres's notification framework. Check out how we do it in the tls observatory: https://github.com/mozilla/tls-observatory/blob/master/database/messaging.go#L84-L88

For recurring scans, I personally prefer to just drive those from the outside by calling the API from a cron job somewhere.

**Comment by gdestuynder** [comment]
notify/trigger > polling.
rmq is complex to run.

pg notify is something I haven't used before, but looks neat (https://www.postgresql.org/docs/9.0/static/sql-notify.html).

It does use a socket thus there is an os-specific poll/trigger (generally epoll trigger on linux), thus this is the same as rmq except all of it is pre-handled by pgsql and it's libraries.

To make the best use of it, it appears that the db which stores the scan results need to be the same db instance/process group ("master pg") that does the notification, as the table updates are what trigger notifications (which is logical). This also means that the API does not have to directly trigger jobs (though it also can), it can still do so via pgsql, and is still quite logical. Each component "just" need a listener, or a specific payload in a listener. A sequence diagram should make these things clear for implementation.

This means the diagram would have the database and notifier/scheduler on the same instance. I suppose that with a clear database schema this is fine - though it does mean it no longer separate the queue from the db storage area. Seems like a good trade off for a project of this size though.

The alternative is to use something like zeromq, or own socket-based msg that does pretty much the same thing anyway, so pgsql is probably one of the best solutions.

**Comment by claudijd** [comment]
Also, consider making LetEncrypt the default/favorable for certs on the API

**Comment by claudijd** [comment]
Expectations were re-adjusted in this weeks MWoS meeting.  We're now aiming for something like this, which will be iterated on once we have a functional end-to-end implementation.  Components are pretty modular, so it's easy to switch/upgrade things, but the general perception has been, to keep it simple until we can start loading it up with scans and see how well it works.

<img width="624" alt="screen shot 2016-12-02 at 4 40 42 pm" src="https://cloud.githubusercontent.com/assets/794283/20851383/23aa2784-b8ae-11e6-9b62-73f555688fa3.png">

Today, we're only missing the DB component, which is scheduled to be completed in the next week by the MWoS team.  DB store issue can be found here (https://github.com/mozilla/ssh_scan/issues/266)

**Comment by claudijd** [comment]
Additionally, the diagram doesn't make this entirely clear, but to start we'll just have a single worker process running on the API/DB server and work from there with the knowledge that if we need to scale more, we can just add more workers local/remote.
