### ISSUE TITLE
Provide a caching feature in the API to retrieve pre-existing scan result rather than re-task a worker

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan#296]
The basic problem statement is what User A and User B request the same scan within say 15min of each other.  How do we avoid doing the work twice?

**Solution:** provide a caching feature in the API that will retrieve a pre-existing scan from the database rather than handing this work off to a worker.

**Comment by rishabhs95** [comment]
The basic caching functionality was included in PR#305. As the DB functionality is landed successfully, I am working to complete the missing parts of the functionality.

Currently, caching functionality just looks for the already present records and if a record is present (i.e, target is already scanned), we return its `uuid` instead of sending a new job to the worker. I think that we can move forward with these steps:

- We let the above functionality remain same.
- Additionally, we now also remove the already present scan in our DB for a target which is forced for a re-scan. So now, whenever the user requests the same target, they will receive the latest scan results.

I think that this should suffice our need for now. Do you think that we should also check for timestamps, for example, if the present scan in the DB is more than 2 days ago, initiate a re-scan and replace its result with the older one? @claudijd @agaurav77 @royalharsh

**Comment by royalharsh** [comment]
Yeah, I think we should implement it. So that users get the latest scan.

**Comment by rishabhs95** [comment]
Yeah, I was equally tending towards both the ways. I have included the timeouts for 1 day anyways in my PR.

**Comment by claudijd** [comment]
This was done a long time ago, closing.
