### ISSUE TITLE
Propose sshd_config lines in the recommendations

### ISSUE THREAD

**Issue by paulehoffman** [mozilla/ssh_scan#340]
This is a lovely tool. When I point it to one of my servers whose sshd_config has no uncommented lines, the result is:
```
. . .      "recommendations": [
        "Remove these Key Exchange Algos: diffie-hellman-group-exchange-sha1, diffie-hellman-group14-sha1, diffie-hellman-group1-sha1",
        "Remove these MAC Algos: hmac-md5-etm@openssh.com, hmac-sha1-etm@openssh.com, umac-64-etm@openssh.com, hmac-ripemd160-etm@openssh.com, hmac-sha1-96-etm@openssh.com, hmac-md5-96-etm@openssh.com, hmac-md5, hmac-sha1, umac-64@openssh.com, hmac-ripemd160, hmac-ripemd160@openssh.com, hmac-sha1-96, hmac-md5-96",
        "Remove these Encryption Ciphers: arcfour256, arcfour128, aes128-cbc, 3des-cbc, blowfish-cbc, cast128-cbc, aes192-cbc, aes256-cbc, arcfour, rijndael-cbc@lysator.liu.se",
        "Remove these Authentication Methods: keyboard-interactive"
      ], . . .
```
It would be grand if the recommendations also had something along the lines of "To implement these recommendations for a host that you control, add the following lines to sshd_config: \nCiphers  aes256-gcm@openssh.com ..."

**Comment by claudijd** [comment]
@paulehoffman thanks for your suggestions!  Here's a couple consideration I have on this topic...

1.) Policies would need to describe ssh lib specific recommendations because not everything is running OpenSSH.  This could increase the size, complexity, and redundancy of each policy.  Not necessarily a bad thing, but a likely outcome.  Example policy (https://github.com/mozilla/ssh_scan/blob/master/config/policies/mozilla_modern.yml)
2.) What would be the desired behavior if we come across an implementation where the SSH lib is either unknown or not seen before and we don't how how it would be expressed in config?  Would we revert back the legacy strategy?
3.) In a use case where you're dealing with an older version of an SSH lib, but it doesn't support or error when the additional lib is set in the config, does this make it harder for the end user to know the exact reason why we're saying that particular attribute is what's causing the compliance failure.
4.) If you're running OpenSSH, I have included a reference section to the scan output that points you to docs which can be found here in the policy config (https://github.com/mozilla/ssh_scan/blob/master/config/policies/mozilla_modern.yml#L30).

I would love your feedback on the above so I can take those consideration in how we might evolve this to it's easier for you and others to use.
