### ISSUE TITLE
Running with --unit-test throws an error

### ISSUE THREAD

**Issue by jvehent** [mozilla/ssh_scan#419]
The scan succeeds and returns the JSON, but then fail with
```
$ docker run -it mozilla/ssh_scan /app/bin/ssh_scan -t 72.64.221.62 -P config/policies/mozilla_modern.yml --unit-test

... lots of json...

/app/bin/ssh_scan:264:in `block in <main>': undefined method `compliant' for #<Hash:0x00000001717f90> (NoMethodError)
Did you mean?  compact
        from /app/bin/ssh_scan:263:in `each'
        from /app/bin/ssh_scan:263:in `<main>'
```

**Comment by claudijd** [comment]
I can repro the bug outside of docker instance, so it appears to affect both native and docker environments.  I'll try to get this fixed up shortly.

**Comment by claudijd** [comment]
Bug is fixed in https://github.com/mozilla/ssh_scan/pull/420  I will be releasing a new version of ssh_scan as soon as it's landed in master.

**Comment by claudijd** [comment]
gem version 0.0.29 has been released to address this issue

I also confirmed the latest docker container should be also fixed, because that was your original repro scenario...

docker run -it mozilla/ssh_scan /app/bin/ssh_scan -t 72.64.221.62 -P config/policies/mozilla_modern.yml --unit-test

^^^ now works on latest.

**Comment by claudijd** [comment]
Thanks again for the bug report!
